[package]
name = "bevy_mod_wanderlust"
version = "0.1.1"
authors = ["PROMETHIA-27"]
edition = "2021"
description = "A character controller library for Bevy Engine"
# documentation = 
readme = "README.md"
homepage = "https://crates.io/crates/bevy_mod_wanderlust"
repository = "https://github.com/PROMETHIA-27/bevy_mod_wanderlust"
license = "MIT OR Apache-2.0"
keywords = ["Bevy"]
categories = ["game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_rapier3d = { version = "0.15.0", features = ["debug-render"] }

[dev-dependencies]
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls" }

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3